# Generated by Django 5.1.4 on 2025-01-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_selloffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellOffer',
        ),
    ]
