# Generated by Django 5.1.4 on 2025-01-10 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_selloffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nftoken_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.CharField(max_length=20)),
                ('destination', models.CharField(blank=True, max_length=35, null=True)),
                ('offer_index', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
